version: '1.0'
stages:
  - checkout
  - prepare
  - build
  - test

steps:
  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'testillano/json2xml'
    revision: master
    git: github
  build_dev_image:
    title: Building Dev Image
    stage: prepare
    type: build
    image_name: 'testillano/${{CF_REPO_NAME}}-dev'
    tag: 'latest'
    dockerfile: ./dev/Dockerfile
  create_makefiles:
    title: Create Makefiles
    stage: prepare
    image: ${{build_dev_image}}
    commands:
      - cmake .
  compile_my_sources:
    title: Compile
    stage: build
    image: ${{build_dev_image}}
    commands:
      - make
  build_test_image:
    title: Building Test Image
    stage: prepare
    type: build
    working_directory: ./ct
    image_name: 'testillano/${{CF_REPO_NAME}}-ct'
    tag: 'latest'
    dockerfile: Dockerfile
  run_my_tests:
    title: Test
    stage: test
    image: ${{build_test_image}}
    commands:
      - cd ct
      - pytest
